version: '3'

services:
  # Contenedor nginx, balanceador de carga
  nginx:
    container_name: nginx-container
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

  # Replicacion, db master
  mysql_master:
    image: mysql:latest
    container_name: mysql_master
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica --bind-address=0.0.0.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica

  # Replicacion, db esclavo
  mysql_slave:
    image: mysql:latest
    container_name: mysql_slave
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica

# Gestion por phpMyAdmin 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: "mysql_master,mysql_slave"
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_master
      - mysql_slave
    ports:
      - "8080:80"

  # contenedor 1 wordpress
  wordpress1:
    image: wordpress:latest
    container_name: wordpress-1
    ports:
      - "8081:80"
    environment:
      - WORDPRESS_DB_HOST=mysql_master
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=replica
      - WORDPRESS_TABLE_PREFIX=wp1_

  # contenedor 2 wordpress
  wordpress2:
    image: wordpress:latest
    container_name: wordpress-2
    ports:
      - "8082:80"
    environment:
      - WORDPRESS_DB_HOST=mysql_master
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=replica
      - WORDPRESS_TABLE_PREFIX=wp2_

  # contenedor 3 wordpress
  wordpress3:
    image: wordpress:latest
    container_name: wordpress-3
    ports:
      - "8084:80"
    environment:
      - WORDPRESS_DB_HOST=mysql_master
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=replica
      - WORDPRESS_TABLE_PREFIX=wp3_